---

- name: configuration
  hosts: all
  gather_facts: false # remove later! speeds up testing
  become: true
  roles:
    - configuration


- name: deploy tomcat
  hosts: apps
  gather_facts: false
  become: true
  roles:
    - app-tier

- name: deploy haproxy
  hosts: frontends
  gather_facts: false # remove later! speeds up testing
  become: true  
  roles:
   - lb-tier

- name: install and start Postgres
  hosts: appdbs
  become: yes
  roles:
   - db-tier


