---
# tasks file for roles/app-tier
- name: install "{{ payload }}"
  package:
    name: "{{ payload }}"
    state: latest
  notify:
    - start tomcat

- name: enable tomcat at boot
  service:
    name: "{{ payload }}"
    enabled: yes

- name: create ansible tomcat directory
  file:
    path: "{{ tomcat_web_root }}"
    state: directory

- name: copy static index.html to tomcat webapps/ansible/index.html
  template:
    src: index.html.j2
    dest: "{{ tomcat_web_root }}/index.html"
    mode: 0644





